### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by mhekeler** [graemeg/fpGUI#15]
I wonder how to set an Icon?!?

Okay - for Windows its possible to set a Icon and thereś no such think for linux. That's okay. 

But all of my fpGUI Windows have a small fpGUI-Symbol in the left corner. What is this called? And how can I set this behaviour?

**Comment by graemeg** [comment]
I know this reply is very late... :-/ I was working through open tickets.  I'm assuming you are using a fpGUI version before the IconName property was implemented.  If you get a copy of the **fixes_1.4** branch, or any later version, then you will find the TfpgForm.IconName property.

**Usage:**
```Pascal
procedure TMainForm.AfterCreate;
begin
   ...
   IconName := 'stdimg.folderhome';

   // create the rest of your widgets here
end;
```

If you now run your application the "folderhome" icon will be shown instead of the black & white FPGUI logo.
