### ISSUE TITLE
button of scrollbar is blank on Linux

### ISSUE THREAD

**Issue by saulery** [graemeg/fpGUI#67]
Hello Greame,

I such a GUI toolkit for a little sqlite database application. I find some time to discover fpGUI and play with yours samples on Linux but my target is Windows for this time.

With dev. codebase, in maximus and others examples, the buttons on scrollbars are blank. An image is better than a long text :

![maximus_2017-11-02_23-03-51](https://user-images.githubusercontent.com/10128284/32352706-a52ad390-c022-11e7-858a-cb0e52304efd.png)

Regards,

**Comment by graemeg** [comment]
Thank you for reporting it. It is a known bug. The **develop** branch is still heavily under development since the **alien_window** and **aggpas_canvas** branch merges. I still have lots of work to do to get it back into a stable state.  For production work, I recommend you use the **maint** branch for now - though I do appreciate any testing and feedback on the **develop** branch.

**Comment by graemeg** [comment]
I'm glad to report that the issue should now be fixed. As of commit 28c461af.

**Comment by saulery** [comment]
Tested, it's working. Thanks a lot.

**Comment by saulery** [comment]
It's been a very long time I have not written Pascal code (20 years). I can help you for testing on Windows, maybe on Linux if I setup a new machine.
