### ISSUE TITLE
examples\corelib\aggcanvas example is broken

### ISSUE THREAD

**Issue by saulery** [graemeg/fpGUI#71]
The example in examples\corelib\aggcanvas doesn't compile because agg2D unit is not available in lib directory when I compile fpGUI. Is this expected?

**Comment by graemeg** [comment]
Did you see the IMPORTANT note in the unit comment about compiling the example?

>     *** IMPORTANT ***
>      For this demo to work, the fpGUI Toolkit MUST be compiled with
>      the AggCanvas compiler define enabled.

So did you compile the fpGUI toolkit code with the _AggCanvas_ compiler define enabled?

If you use the _fpgui_toolkit.lpk_ Lazarus Package, then take a look under "Options -> Compiler Options -> Custom Options". By default the _AggCanvas_ is disabled. Removed the trailing "X" and recompile.

I'll see if there is an easier way to make the demo compilable.

**Comment by saulery** [comment]
No. It was under my nose and I didn't see. For this time I did not use Lazarus. I have used build.bat or build.sh on terminal only.

**Comment by graemeg** [comment]
Please get an update and try again. I've extended the demo so that the _extrafpc.cfg_ file includes everything it needs to compile, and simply doesn't use the < fpgui >/lib/ compiled units. The only manual requirement now is to create the "units" output directory.

I'm planning on reworking all the demos so they almost act like unit tests for fpGUI - or maybe merge them all into one single (large) demo - I'm still undecided.

Anyway, if it compiles now for you from the command line, then I'll close the bug report.

**Comment by saulery** [comment]
Thanks a lot! It's working now.

Have you see my PR about demo compilation? I think you will drop it if you rework all that stuff.

**Comment by graemeg** [comment]
Thanks for confirming. I'll take a look at your pull request next.
